rapoapp/urls.py
import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import allauth
from allauth.account.views import logout
from django.contrib import admin
admin.autodiscover()

from allauth.socialaccount.models import SocialAccount
from rapocore.views import ReleaseBook,ReceiveBook,SendBook, GetMembers, WriteBookReview, WithdrawBook
from rapocore.views import Search, Browse, SearchResults, PassOn,PassOnBook, Test, MyAccount, FeedbackPage
from rapocore.views import NewAuthor,NewLanguage, NewGenre, ReportDefect, DefectListView, MemberListView, MemberProfile
from rapocore.models import Book


urlpatterns = patterns('',
    url(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'), 
    url(r'^admin/', include(admin.site.urls)),#why not quotes ?SM


    #url(r'^$', TemplateView.as_view(template_name="underconstruction.html"), name="index"),
    url(r'^$', 'allauth.account.views.login',name='login'),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="index"),
    url(r'^about/', TemplateView.as_view(template_name="about.html"), name="index"),
    #url(r'^contact/', TemplateView.as_view(template_name="contact.html"), name="index"),
    url(r'^readme$', TemplateView.as_view(template_name="rapocore/readme.html"), name="index"),
    url(r'^disclaimer$', TemplateView.as_view(template_name="rapocore/disclaimer.html"), name="disclaimer"),
    url(r'^meet1$', TemplateView.as_view(template_name="rapocore/rapofirstmeet.html"), name="meet1"),
    url(r'^contest1$', TemplateView.as_view(template_name="rapocore/ReviewContestDec2013.html"), name="meet1"),

    url(r'^thanks/', TemplateView.as_view(template_name="rapocore/thanks.html"), name="thanks"),

    url(r'^accounts/profile/','rapocore.views.MyAccount' ,name='myaccount'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/memberprofile/(?P<username>.*)/', 'rapocore.views.MemberProfile',name='member-profile'),
    url(r'^logout/', 'allauth.account.views.logout',name='logout'),
    url(r'^feedback/', 'rapocore.views.FeedbackPage', name="feedback"),
    url(r'^meets/', 'rapocore.views.MeetsHome', name="meets"),
    url(r'^qea/', 'rapocore.views.QEAHome', name="qea"),
    url(r'^howitworks/', TemplateView.as_view(template_name="rapocore/howitworks.html"), name="howitworks"),
    #url(r'^feedbacklist/', 'rapocore.views.FeedbackList', name="feedback-list"),
    #url(r'^feedbackdetails/(?P<feedbackid>\d+)/$', 'rapocore.views.FeedbackDetails', name="feedback-details"),    

    url(r'^releasebook/', 'rapocore.views.ReleaseBook',name='release-book'),
    url(r'^withdrawbook(?P<bookid>[0-9]*)/', 'rapocore.views.WithdrawBook',name='withdraw-book'),
    url(r'^sendbook/', 'rapocore.views.SendBook',name='send-book'),
    url(r'^getmembersinqueue/(?P<bookid>[0-9]*)/', 'rapocore.views.GetMembers',name='send-book-get-members'),
    url(r'^receivebook/', 'rapocore.views.ReceiveBook',name='receive-book'),
    url(r'^passon/', 'rapocore.views.PassOn',name='pass-on'),
    #url(r'^searchby(?P<byfield>.*)/$', 'rapocore.views.Search',name='search'),
    url(r'^search/', 'rapocore.views.Search',name='search'),
    url(r'^searchresults', 'rapocore.views.SearchResults',name='search-results'),
    url(r'^bookbrowse/', 'rapocore.views.Browse', name='book-browse'),
# Benitha to work on Browse details page and view queue page : Date: 06-Nov-2013 	
    url(r'^bookdetails/(?P<bookid>\d+)/$', 'rapocore.views.BookDetails', name='book-details'),
    url(r'^viewqueue/(?P<bookid>\d+)/$', 'rapocore.views.ViewQueue', name='view-queue'),

    #url(r'^memberbrowse/', MemberListView.as_view(),name='member-browse'),
    url(r'^writebookreview/(?P<bookid>\d+)/$', 'rapocore.views.WriteBookReview', name='write-bookreview'),
    url(r'^rapobookreviewslist/(?P<bookid>\d+)/$', 'rapocore.views.RAPOBookReviewsList', name='rapo-bookreview-list'),
    url(r'^rapobookreviewsdetails/(?P<bookid>\d+)/(?P<reviewid>\d+)/$', 'rapocore.views.RAPOBookReviewsDetails', name='rapo-bookreview-details'),
    
    url(r'^addauthor/', 'rapocore.views.NewAuthor',name='add-author'),
    url(r'^addgenre/', 'rapocore.views.NewGenre',name='add-genre'),
    url(r'^addlanguage/', 'rapocore.views.NewLanguage',name='add-language'),
    url(r'^add2queue(?P<bookid>[0-9]*)/$', 'rapocore.views.Add2Queue',name='add-queue'),
    url(r'^cancelrequest(?P<bookid>[0-9]*)/$', 'rapocore.views.CancelRequest',name='cancel-request'),
    url(r'^archiveit(?P<defectid>[0-9]*)/$', 'rapocore.views.Archiveit',name='archiveit'),
    url(r'^closeit(?P<defectid>[0-9]*)/$', 'rapocore.views.Closeit',name='closeit'),
    url(r'^passon(?P<bookid>[0-9]*)/$', 'rapocore.views.PassOnBook',name='passon-book'),

    url(r'^defect/', 'rapocore.views.ReportDefect',name='report-defect'),
    url(r'^defectbrowse/', DefectListView.as_view(),name='defect-browse'),
    url(r'^memberbrowse/', MemberListView.as_view(queryset=SocialAccount.objects.order_by("user__first_name","user__last_name")),name='member-browse'),
    url(r'^$', 'allauth.account.views.login',name='login'),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

)


urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
	    url(r'^static/(?P<path>.*)$', 'serve'),
)

rapoapp/rapocore/models.py
# Create your models here.

from django.db import models
from datetime import datetime
from datetime import date
from django.contrib.auth.models import User
from django.forms import ModelForm
from allauth.socialaccount.models import SocialAccount
from rapogen.models import Book,Author,Genre, Language



class RealBook(models.Model):
    AVAILABLE='A'
    READ='R'
    TRANSIT='T'
    BOOKED='B'
    LOST='L'
    DELETED='D'
    STATUS_CHOICES = (
        (AVAILABLE,'Available'),
        (READ,'Reading'),
        (TRANSIT,'In Transit'),
        (BOOKED,'Reserved'),
        (LOST,'Lost'),
        (DELETED,'Deleted'),
    )
    book= models.ForeignKey(Book)
    ownermember = models.ForeignKey(SocialAccount,related_name='OriginalOwner',verbose_name='Original Owner')
    withmember = models.ForeignKey(SocialAccount,related_name='CurrentlyWith',verbose_name='Currently with')
    status = models.CharField(max_length=1,choices=STATUS_CHOICES,default=AVAILABLE)
    datereleased = models.DateTimeField( verbose_name='Date of release',auto_now_add=True)
    rqueue = models.ManyToManyField(SocialAccount,through='Queue',related_name='Queue',verbose_name='Reservation Queue')
    fb_permalink = models.TextField(null=True,blank=True)
    comments = models.TextField(null=True,blank=True)
    def __unicode__(self):
        return self.book.title
    class Meta:
        ordering = ['book']

    @property
    def is_new(self):
        if (date.today() -  self.datereleased.date()).total_seconds() < 604800:  # 7 days
           return True
        return False

class Transaction(models.Model):
    REC='R'
    SEN='S'
    SHARED = 'D'
    NA = 'N'
    CHARGE_CHOICES = (
        (REC,'Receiver'),
        (SEN,'Sender'),
        (SHARED,'Shared'),
        (NA,'Not Applicable'),
    )
    book = models.ForeignKey(RealBook)
    from_member = models.ForeignKey(SocialAccount,related_name='from')
    to_member = models.ForeignKey(SocialAccount,related_name='to')
    date_sent = models.DateTimeField()
    date_received = models.DateTimeField(null=True,blank=True)
    via = models.CharField(max_length=100,null=True,blank=True)
    tracking = models.CharField(max_length=256,null=True,blank=True,verbose_name='Tracking id/url')
    charges = models.CharField(max_length=20,null=True,blank=True)
    charges_on = models.CharField(max_length=1,choices=CHARGE_CHOICES,default=NA)
    comments = models.TextField(null=True,blank=True)

    class Meta:
            ordering = ['date_sent']
            unique_together =(('book','from_member','to_member','date_sent'),)

    def __unicode__(self):
        return u'%s : %s %s --> %s %s ON %s' % (self.book,self.from_member.user.first_name,self.from_member.user.last_name,self.to_member.user.first_name,self.to_member.user.last_name,self.date_sent)

class Queue(models.Model):
    book = models.ForeignKey(RealBook)
    member = models.ForeignKey(SocialAccount)
    class Meta:
        ordering = ['id']
        unique_together =(('book','member'),)
    def __unicode__(self):
        return "%s " % (self.book.title)


class Defect(models.Model):
    OPEN='OP'
    CLOSED='CL'
    NOTDEFECT='ND'
    INFUTURE='FU'
    ARCHIVED='AR'
    DEFECT_STATUS_CHOICES = (
        (OPEN,'Open'),
        (CLOSED,'Closed'),
        (NOTDEFECT,'Not a defect'),
        (INFUTURE,'In future'),
        (ARCHIVED,'Archived'),
    )
    SITEFUNCTIONALITY='SF'
    BOOKRELATED='BK'
    AESTHETIC='AE'
    DESIRABLE='DE'
    OTHER='OT'
    DEFECT_CATEGORY_CHOICES = (
        (SITEFUNCTIONALITY,'Site functionality'),
        (BOOKRELATED,'Books Entry related'),
        (AESTHETIC,'Aesthetic'),
        (DESIRABLE,'Desirable feature'),
        (OTHER,'Other'),
    )
    description = models.TextField() 
    category = models.CharField(max_length=2,choices=DEFECT_CATEGORY_CHOICES,default=OTHER)
    bymember = models.ForeignKey(SocialAccount,related_name='By')
    logdate = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2,choices=DEFECT_STATUS_CHOICES,default=OPEN)
    fixedon = models.DateTimeField(null=True,blank=True)
    comments = models.TextField(null=True,blank=True)
    def __unicode__(self):
        return self.description
    class Meta:
        ordering = ['-logdate']

# Benitha: 13-Nov-2013 Model for book cover img
#class Document(models.Model):
#       docfile = models.FileField(upload_to='documents/%Y/%m/%d')

rapoapp/templates/rapocore/addanother.html
{% load i18n admin_static admin_list %} 
{% load admin_urls %} 

<html>
    <head>
        <title>Add {{ field }}</title>
        <script type="text/javascript" src="{% static "/admin/js/admin/RelatedObjectLookups.js" %}"></script>
    </head>
    <body>
        <h1>Add {{ field }}</h1>
        <form method="POST" action="/add{{ field }}/">{% csrf_token %}
            <table>
                {{ form }}
            </table>
            <p><input type="submit" value="Add {{ field }}" /> | <a href="javascript:window.close()">Cancel</a></p>
        </form>
    </body>
</html>

rapoapp/templates/rapocore/archiveit.html
{% load i18n admin_static admin_list %} 
{% load admin_urls %} 


<html>
    <head>
        <title>Archive it</title>
	<link rel="stylesheet" type="text/css" href="{% static "admin/css/bootstrap.min.css" %}" /> 
	<script>
        window.onunload = refreshParent;
        function refreshParent() {
            window.opener.location.reload();
        }
    </script>
    </head>
    <body>
	<h1>Archived </h1>
    <div class="container">
    <div class="col-sm-9">
			<p>{{ user.first_name }} {{ user.last_name }} successfully archived defect "{{ defect }}"</p>
            <p><a href="javascript: window.close();"/>Close</p></a>
	</div>
	</div>
    </body>
</html>

rapoapp/templates/rapocore/cancelrequest.html
{% load i18n admin_static admin_list %} 
{% load admin_urls %} 


<html>
    <head>
        <title>Cancel request</title>
	<link rel="stylesheet" type="text/css" href="{% static "admin/css/bootstrap.min.css" %}" /> 
	<script>
        window.onunload = refreshParent;
        function refreshParent() {
            window.opener.location.reload();
        }
    </script>
    </head>
    <body>
    <div class="container">
    <div class="col-sm-9">
        {% if success %}
        	<h1>Removed from queue </h1>
			<p>{{ user.first_name }} {{ user.last_name }}  successfully removed from  queue for {{ book }}</p>
        {% else %}
        	<h1>Already sent to you </h1>
			<p>{{ book }} already sent to  {{ user.first_name }} {{ user.last_name }} </p>
	</div>
	</div>
        {% endif %}
				
   <p><a href="javascript: window.close();"/>Close</p></a>
    </body>
</html>

rapoapp/templates/rapocore/dashboard.html
{% extends "rapocore/myaccount.html" %}

{% load i18n admin_static admin_list %} 
{% load admin_urls %} 
{% load staticfiles %} 

{% block title %}
{{ block.super }} My Account
{% endblock %}

{% block headsection %}
{{ block.super }}
<script type="text/javascript" src="{% static "sorttable.js" %}"></script> 
<script>

function popitup(url,message) {
	var response= confirm(message) 
		if (response==true){
			newwindow=window.open(url,'{{title}}','height=200,width=1000');
			if (window.focus) {newwindow.focus()}
		}
	return false;
}
/*
   function ToggleList(IDS) {
   var CState = document.getElementById(IDS);
   if (CState.style.display != "table-row") { CState.style.display = "table-row"; }
   else { CState.style.display = "none"; }
   }*/

</script>

{{ form.media }}
{% endblock headsection %}

{% block topsection %}
{{ block.super }} 
{% endblock topsection %}

{% block Centre %}
<div class="panel panel-success">
	<div class="panel-heading">
		<strong>Books with me</strong>
	</div>
	<div class="panel-body">
		<table class="table table-hover" >
			{% comment %} Books currently with me {% endcomment %}
			<thead>
				<tr>
					<th>Title</th>
					<th>Status</th>
				</tr>
			</thead>
			{% for bk in bookswith %} 
    		<tr> <td> <a href = "/bookdetails/{{ bk.id }}" title="Click to view the details of the book" >{{ bk.book.title }}</a> </td>
				{% ifnotequal bk.rqueue.count 0 %} 
				<td> In queue : </br>  {% for m in bookswithqlist %} 
					{% ifequal bk.id m.book__id %}  
			                <a href="/accounts/memberprofile/{{ m.member__user__username }}/">{{ m.member__user__first_name }} {{ m.member__user__last_name }}</a>
					{% comment %}
					{% ifequal user.is_staff 1 %}
					<a href="/sendbookto{{ m.uid }}/{{ book.id }}">Send Book</a>   
					{% endifequal %}
					{% endcomment %}
					</br>  {% endifequal %}
					{% endfor %} </td>
				{% else %}
				<td> {{ bk.get_status_display }} 
					{% ifequal bk.status 'A' %}
						{% ifequal bk.ownermember bk.withmember %}
							<a href="/withdrawbook{{ bk.id }}" title="Click to withdraw this book" onclick="return popitup(this,'Are you sure you want to withdraw this book - {{ bk.book.title }}?');">Withdraw Book</a>
						{% endifequal %}
					{% endifequal %}
				</td> 
				{% endifnotequal %}
			</tr> 
			{% endfor %} 

</table>
</div>
</div>
			{% comment %} Books in transit {% endcomment %}
			{% if booksintransitfromme %}  
<div class="panel panel-success">
		  <div class="panel-heading">
		    <strong>Books In Transit from Me</strong>
		  </div>
  <div class="panel-body">
<table class="table table-hover">

			<th> Title </th>  <th> To </th></tr>
		{% for tr in booksintransitfromme %} <tr> <td> <a href = "/bookdetails/{{ tr.book.id }}" title="Click to view the details of the book" >{{ tr.book.book.title }}</a> </td> <td>  --> <a href="/accounts/memberprofile/{{ tr.to_member__user__username }}/">{{ tr.to_member__user__first_name }} {{ tr.to_member__user__last_name }}</a> ON {{ tr.date_sent }} </td></tr> {% endfor %} 
			                
    		
</table>
</div>
</div>
{% endif %}

{% if booksintransittome %}
 <div class="panel panel-success">
		  <div class="panel-heading">
		    <strong>Books In Transit to Me</strong>
		  </div>
  <div class="panel-body">
<table class="table table-hover">
		<th> Title </th>  <th> From </th></tr>
	{% for tr in booksintransitfromme %} <tr> <td> <a href = "/bookdetails/{{ tr.book.id }}" title="Click from view the details of the book" >{{ tr.book.book.title }}</a> </td> <td>  <-- <a href="/accounts/memberprofile/{{ tr.from_member__user__username }}/">{{ tr.from_member__user__first_name }} {{ tr.from_member__user__last_name }}</a> ON {{ tr.date_sent }} </td></tr> {% endfor %}

</table>
</div>
</div>
 {% endif %}

	{% comment %} Books requested by me {% endcomment %}
<div class="panel panel-success">
		  <div class="panel-heading">
		    <strong>Books Requested by Me</strong>
		  </div>
  <div class="panel-body">
<table class="table table-hover">
	{% if booksrequested %} 
  <thead>
	  <tr>
<th>Title</th>
<th>Currently With</th>
	  </tr>
	</thead>
{% for qu  in booksrequested %} <tr> <td> <a href = "/bookdetails/{{ qu.book.id }}" title="Click to view the details of the book" >{{ qu.book.book.title }}</a> </td> <td> <a href="/accounts/memberprofile/{{ qu.book.withmember.user.username }}/"> {{ qu.book.withmember.user.first_name }} {{ qu.book.withmember.user.last_name }}</a> </td> </tr> {% endfor %} </td> </tr>
{% else %}
<tr> <td>No books requested </td> </tr>
{% endif %}
</table>
</div>
</div>



{% comment %} Books released by me {% endcomment %}

<!--<a href="#" color = "#ff00ff" onclick="ToggleList('a')">Books released by me</a> -->
<div class="panel panel-success">
		  <div class="panel-heading">
		    <strong>Books Released by Me</strong>
		  </div>
  <div class="panel-body">
<table class="table table-hover">
  <thead>
	  <tr>
<th>Title</th>
<th>On</th>
<th>Currently With</th>
	  </tr>
	</thead>
{% for bk in booksreleased %} <tr> <td> <a href = "/bookdetails/{{ bk.id }}" title="Click to view the details of the book" >{{ bk.book.title }}</a> </td><td>  {{ bk.datereleased }} </td> <td><a href="/accounts/memberprofile/{{bk.withmember.user.username}}/">{{ bk.withmember.user.first_name }} {{ bk.withmember.user.last_name }}</a></td> </tr> {% endfor %} </td> </tr>
</table> 
</div>
</div>


{% endblock %}

rapoapp/templates/rapocore/defect_list.html
{% extends "rapocore/myaccount.html" %}

{% load i18n admin_static admin_list %} 
{% load admin_urls %} 

{% block title %}
{{ block.super }} Browse Defects
{% endblock %}

{% block headsection %}
{{ block.super }}
<script type="text/javascript" src="{% static "sorttable.js" %}"></script> 
<script language="javascript" type="text/javascript">
<!--
function popitup(url,message) {
    var response= confirm(message) 
    if (response==true){
        newwindow=window.open(url,'{{title}}','height=200,width=1000');
        if (window.focus) {newwindow.focus()}
    }
    return false;
}

// -->
</script>
{{ form.media }}
{% endblock headsection %}

{% block topsection %}
{{ block.super }} 
{% endblock topsection %}
	
{% block Centre %}
<div class="panel panel-success">
     <div class="panel-heading">
     <strong>Defects</strong>
</div>
<table id="defects" class="table" style="table-layout:fixed">
	<thead>
   	<tr>
	<th style="width: 20%" id="by"> Logged by </th>
	<th  style="width:15%" id="date"> Log date</th>
	<th style="width: 15%"  id="cat"> Category </th>
	<th style="width: 28%"  id="desc"> Description </th>
	<th style="width: 15%"  id="comm"> Comments </th>
	<th style="width: 7%"  id="stat"> Status </th>
	</tr>
</thead>
{% for defect in object_list %}
    {% ifnotequal defect.status 'AR' %}
   	<tr>
			<td><a href="/accounts/memberprofile/{{ defect.bymember.user.username }}/">{{ defect.bymember.user.first_name }} {{defect.bymember.user.last_name }}</a></td>
			<td>{{ defect.logdate|date:"Y/m/d h:i:s A" }}</td>
			<td>{{ defect.get_category_display }}</td>
			<td>{{ defect.description }} </td>
			<td>{{ defect.comments }} </td>
			<td class="{{ defect.get_status_display|lower }}status">{{ defect.get_status_display }} {% ifequal user.is_staff 1 %}
                {% ifnotequal defect.status 'CL' %}
				<a href="/closeit{{ defect.id }}" id="closeit" class="closeit" onclick="return popitup(this,'Are you sure you want to close this defect?');">Close it</a> 
                {% else %}
				<a href="/archiveit{{ defect.id }}" id="archiveit" class="archiveit" onclick="return popitup(this,'Are you sure you want to archive this defect?');">Archive it</a> </br>
                {% endifnotequal %}
 				{% endifequal %}</td>
			
	</tr>
    {% else %}
       {% ifequal user.is_staff 1 %}
   	       <tr>
			    <td><a href="/accounts/memberprofile/{{ defect.bymember.user.username }}/">{{ defect.bymember.user.first_name }} {{defect.bymember.user.last_name }}</a></td>
	       		<td>{{ defect.logdate|date:"Y/m/d h:i:s A" }}</td>
	       		<td>{{ defect.get_category_display }}</td>
	       		<td>{{ defect.description }} </td>
	       		<td>{{ defect.comments }} </td>
	       		<td class="{{ defect.get_status_display|lower }}status">{{ defect.get_status_display }} </td>
	       		
	       </tr>
       {% endifequal %}
    {% endifnotequal %}
{% empty %}
    <tr class="odd">No defects yet.</tr>
{% endfor %}
   <tfoot><tr> <td class="closedstatus" colspan="8"> {{ object_list.count }} defects logged </td> </tr>
		<tr> <td class="closedstatus" colspan="8"> {{ archived.count }} defects archived </td> </tr> </tfoot>
</table>
</div>
{% endblock %}

rapoapp/templates/rapocore/feedback_details.html
{% extends "rapocore/myaccount.html" %}

{% block title %}
{{ block.super }} {{ formtitle }}
{% endblock %}

{% block headsection %}
{{ block.super }}
{% endblock %}

{% block topsection %}
{{ block.super }} 
{% endblock %}

{% block Centre %}
<div class="panel panel-success">
	<div class="panel-heading">
		<strong>{{ formtitle }}</strong></br>
        {{ formnote }} 
	</div>
	<div class="panel-body">
		<form role="form" method='post' action='/{{ formaction }}/' enctype="multipart/form-data">{% csrf_token %}
			<table>
			{% for field in form %}
				<tr>
					<td>
						{{ field.label_tag }}
						<!--{% ifequal field.name "comments" %}<span class="required">*</span> {% endifequal %}-->
					</td>
					<td>
						{{ field }}
						{{ field.errors }}
					</td>
				</tr>
			{% endfor %}
			</table>
			<input type="submit" value="{{ submitmessage }}" class="btn btn-default"/>
		</form>
	</div>
</div>
{% endblock %}

rapoapp/templates/rapocore/getmembers.html
{% for m in members %}
    <option value="{{ m.member }}">{{ m.member__user__first_name }} {{ m.member__user__last_name }} ( {{ m.member__user__username }} )</option>
{% endfor %}

rapoapp/templates/rapocore/myaccount.html
{% extends "rapocore/rapobase.html" %}
{% load i18n admin_static admin_list %} 
{% load admin_urls %} 
	 
{% block title %} {{ block.super }} {% endblock title %}
{% block headsection %}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script> 
<script type="text/javascript" src="{% static "admin/js/core.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/admin/RelatedObjectLookups.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/actions.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/calendar.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/admin/DateTimeShortcuts.js" %}"></script>

{% endblock headsection %}

{% block Login %} 
          <ul class="nav navbar-nav navbar-right">
          <li> <a href="#"><span class="text-success"><strong>Hello {{ user.first_name }}!</strong></span></a></li>
	  
	  {% if user.first_name %}
	        <li><img height="50px" width="50px" src="http://graph.facebook.com/{{ user.username }}/picture"></img></li> 
          	<li><a href="/accounts/profile" title="View your RAPO&#153; information">My Account</a></li>
	  	<li class="li-no-hover"> <a href="/logout" class="btn btn-success" title="Click to signout">Logout</a> </li>
	  {% else %}
	        <li><img height="50px" width="50px" src="{% static "admin/img/guest.png" %}"></img></li>
	        <li><img height="50px" width="50px" src="{% static "guest.png" %}"></img></li>
	
 {% comment %}yy
		{% for provider in socialaccount.providers %}
			<a title="{{provider.name}}" class="btn btn-success"  href="{% provider_login_url provider.id process=process %}"  >Authenticate with {{provider.name}}</a>
		{% endfor %}
{% endcomment %}

	  {% endif %}
          

          </ul>
{% endblock %}
	 
{% block Left %} {% include "rapocore/_nav.html" %} {% endblock %}

rapoapp/templates/rapocore/viewqueue.html
<!-- Benitha: 07-Nov-2013 for formatting the queue -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/bootstrap.min.css" %}" /> 
<div class="container">
<div class="row">
<div class="col-sm-3">
<div id="leftcolumn">
<div class="innertube">{% block Left %} {% endblock %}</div>
</div>
</div>
<div class="col-sm-9">
 {% block Centre %} {% endblock %}
</div>
</div>

<div class="panel panel-success">
<div class="panel-heading">
          <strong>People in Queue for the book '{{ book }}'</strong>
</div>

<div>
{% if to_member %}
   In Transit ---> {{ to_member.user.first_name }} {{ to_member.user.last_name }} </br>
{% endif %}
{% if queue %}
            {% for m in queue  %}
		<table id="queue" class="table table-hover" rules="rows">
		  <thead>
		    <th id="queueid" width="20%"> No. in queue </th>
		    <th id="name" width="80%"> Requested By </th>
		  </thead>

		  <tr>
		    <td> {{ forloop.counter }} </td>
                    <td> {{ m.member__user__first_name }} {{ m.member__user__last_name }} </td>
		    </br>
		  </tr>
		</table>
            {% endfor %}
{% else %}
	<table id="none">
    		<th> No Queue details found! </th>
	</table>
{% endif %}
 
            <p align="center"><a href="javascript: window.close();"/>Close</p></a>
</div>
</div>

<div class="row">
<div class="well">Copyright &copy; RAPO&trade; 2013</div>
</div>

</div>